apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hpgxbu5nk-nodejs 
  janus-idp.io/tekton: hpgxbu5nk-nodejs
  backstage.io/kubernetes-id: hpgxbu5nk-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hpgxbu5nk-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml